services:
  database:
    image: mongo:latest
    container_name: mern-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  redis:
    image: redis:8.4.0-alpine
    container_name: mern-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@database:27017/${MONGO_DB_NAME}?authSource=admin
      - REDIS_URL=redis://redis:${REDIS_PORT}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - database
      - redis
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern-frontend
    restart: always
    ports:
      - "5173:${FRONTEND_PORT}"
    environment:
      - VITE_BACKEND_URL=http://localhost:${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - mern-network

volumes:
  mongo-data:
  redis-data:


networks:
  mern-network:
    driver: bridge
